version: '3.8'
services:
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: 'flight-booking-app'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql

  cache:
    image: redis:alpine3.19
    restart: always
    ports:
      - '6379:6379'
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "500mb", "--maxmemory-policy", "allkeys-lru"]
    volumes:
      - cache:/data
volumes:
  db:
    driver: local
  cache:
    driver: local