spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flight-booking-app
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: flightbooking


server:
  port: 8080
# https://excalidraw.com/#json=5RfzbYOpNSyQQSq7kDTI8,yiaR73usF35PwubOi-XmKA