spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flight-booking-app
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      hbm2ddl:
        auto: update
    properties:
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: update.sql
  application:
    name: flightbooking


server:
  port: 8080
# https://excalidraw.com/#json=5RfzbYOpNSyQQSq7kDTI8,yiaR73usF35PwubOi-XmKA